DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS breweries CASCADE;
DROP TABLE IF EXISTS user_favourites CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE breweries (
  id VARCHAR(255) UNIQUE,
  name VARCHAR(255),
  street VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(255),
  postal_code VARCHAR(255),
  country VARCHAR(255),
  phone VARCHAR(255),
  website_url VARCHAR(255)
);

CREATE TABLE user_favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  guest_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  brewery_id VARCHAR REFERENCES breweries(id) ON DELETE CASCADE
);

CREATE TABLE reviews (
  id SERIAL PRIMARY KEY NOT NULL,
  guest_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  brewery_id VARCHAR REFERENCES breweries(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL DEFAULT 0,
  comment VARCHAR(500) NOT NULL
);
